### ISSUE TITLE
Question - What happens when RuntimeError is thrown from plugins

### ISSUE THREAD

**Issue by sushovan23** [alerta/alerta-contrib#156]
Hello,
What is the behavior when RuntimeError is thrown from any of the configured plugins?
Does it try again later or stop execution completely?
Does it try to call other plugins which are configured to send notifications?

I am noticing that once RuntimeError is thrown then rest of plugins are not called & I'm missing out on notifications completely.  Is there a way to enable retries?

**Comment by satterly** [comment]
Yes, if a RuntimeError occurs all downstream plugins will not be run and the alert will be discarded.

A retry of a fatal RuntimeError would just fail again, wouldn't it. I'm not sure what the expected behaviour should be given that it has failed and it will fail again if and when it is called at a later time.

**Comment by sushovan23** [comment]
RuntimeError on one plugin may not be valid for other plugin so instead of discarding the notification completely it can still continue to try for other plugins so that notification can reach via one method?

**Comment by satterly** [comment]
There is a new server configuration option called `PLUGINS_RAISE_ON_ERROR` which is set to `True` by default (to be consistent with old behaviour). Set this to `False` to just log plugins that error and continue to call other plugins that work.
