### ISSUE TITLE
Prometheus Ack timeout from alert not action

### ISSUE THREAD

**Issue by satterly** [alerta/alerta-contrib#337]
**Issue Summary**

Plugin triggers the action to alertManager but timeout is gotten from alert.timeout instead of the action timeout (only available in take_action because it is not available in the alert.history at status_change method.

**Environment**
- OS: [eg. Linux, Mac, Windows]
- API version: [eg. 6.8.1]
- Deployment: [eg. Docker, Heroku, AWS, GCloud, self-hosted]
- For self-hosted, WSGI environment: [eg. nginx/uwsgi, apache/mod_wsgi]

- Database: [eg. MongoDB, Postgres]

- Server config:
  Auth enabled? Yes/No
  Auth provider? Google, GitHub, OpenID, Basic, LDAP, etc
  Customer views? Yes/No
  (or provide the `/config` endpoint output)

- web UI version: [eg. 6.8.1]
- CLI version: [eg. 6.8.1]

**To Reproduce**
2. Click on '....' or Run '...'
4. See error (include command output)

For web app issues, include any web browser JavaScript console errors.

**Expected behavior**

**Screenshots**

**Additional context**

NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.

**Comment by frasy** [comment]
This error is only spotted using the API REST or the CLI because timeout is not asked for using the Web UI and the default timeout can be assumed.

My config is next:
**Environment**
- OS: Linux
- API version: 8.2.0
- Deployment: self-hosted
- For self-hosted, WSGI environment: uwsgi
- Database: Postgres
- Server config:
  Auth enabled? Yes
  Auth provider? LDAP
  Customer views? Yes
- web UI version: 8.0.1
- CLI version: 8.2.0

**To Reproduce**
Steps to reproduce the behavior:
- Set a Prometheus Alert
- Set an ACK over that alert
- Timeout will appear as Alert timeout

**Expected behavior**
When sending an ACK to a prometheus alert I expect to have the timeout I send
```
client.action(id, 'ack', 'Test ACK', '4000')
```
The timeout should be 4000 instead of alert.timeout

**Comment by angarilab** [comment]
I am suffering the same issue that was mentioned in this post. 

I just noticed this today, and It got my crazy to find out this bug
