### ISSUE TITLE
resend email alerts after X minutes/hours

### ISSUE THREAD

**Issue by msupino** [alerta/alerta-contrib#64]
Is there a way to make alerta-mailer resend alerts of still-open issues after X minutes/hours ?

need to be able to "remind" of open alerts by emails.

**Comment by satterly** [comment]
Not at the moment. It would be possible because `alerta-mailer` is a long running daemon which could keep track of all the emails sent with a `status` of `open` and then resend those that are about to expire, perhaps.

Not something I've time to look into myself, however I'd be happy to help if you wanted to try adding this yourself.
